FROM ubuntu:18.04

RUN apt-get update -y && \
apt-get install -y curl && \
apt-get install -y python3 python3-pip python-dev build-essential && \
apt-get install -y libsm6 libxext6 libxrender-dev

RUN apt-get install -y locales && locale-gen en_US.UTF-8
ENV LANG='en_US.UTF-8' LANGUAGE='en_US:en' LC_ALL='en_US.UTF-8'

RUN echo "deb [signed-by=/usr/share/keyrings/cloud.google.gpg] http://packages.cloud.google.com/apt cloud-sdk main" | tee -a /etc/apt/sources.list.d/google-cloud-sdk.list && curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | apt-key --keyring /usr/share/keyrings/cloud.google.gpg  add - && apt-get update -y && apt-get install google-cloud-sdk -y

COPY . /app

WORKDIR /app

RUN pip3 install --upgrade pip && \
pip3 install --upgrade google-cloud-storage && \
pip3 install -r requirements.txt
